spring:
  main:
    banner-mode: off
  application:
    name: guardian-gateway

  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            ssl:
              use-insecure-trust-manager: true